// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'actors': String,
  'country': String,
  'director': String,
  'genre': String,
  'images': [String],
  'imdbRating': Number,
  'language': String,
  'plot': String,
  'poster': String,
  'runtime': String,
  'title': String,
  'totalSeasons': Number,
  'type': String,
  'year': String,
}, {
  timestamps: false,
});

module.exports = mongoose.model('movies', schema, 'movies');
